title: Jakob Koschel
url: "https://jakob-koschel.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: ''

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "/cv.pdf"
 - name: "Contact"
   link: "contact"
